# Generated by Django 5.0.1 on 2024-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0002_product_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='app_2.product'),
        ),
    ]
